### ISSUE TITLE
`oj dl -d` breaks the URL guessing

### ISSUE THREAD

**Issue by Tatamo** [kmyk/online-judge-tools#336]
version: online-judge-tools 0.1.55

`oj submit` fails URL guessing and always requires the passkey confirmation after downloading sample cases by using `oj dl -d`.

## Steps to reproduce
```
oj dl https://atcoder.jp/contests/abc111/tasks/abc111_a -d test
oj s https://atcoder.jp/contests/abc111/tasks/abc111_a main.cpp 
```

##  Expected behavior
```
Are you sure? [y/N]
```

## Actual behavior
```
Are you sure? Please type "abca"
```

**Comment by kmyk** [comment]
This tool doesn't use `oj dl -d DIR` to guess the problem to submit, as the expected behavior.

Those who use `-d` option probably use some unknown directory structure.
The typical structure makes one directory for one contest. `oj dl -d abc111_a URL` followed by `oj s URL abc111_b.py` can happen, so we must ignore the `download` with `-d` option.

Also, I note that this is the feature to check mis-operations. This was important bug if it was false-negative, but this causes only flase-positive and is not important.

**Comment by kmyk** [comment]
`-d test` のときに限って特別扱いすればreproの例だけは回避できるけど、例外を増やしてまで対応することとは思えないのでしません。`-y` オプションを使ってください。
まあ `-y` を付けたくないから Issue が立ってるのに申し訳ないけどどうにもできません。いま online-judge-tools の内部をきちんとライブラリとして整備しようとしているので、これを待ってライブラリとして直接叩いて貰うのがあるべき形の解決策かなと思います。

**Comment by kmyk** [comment]
(どうでもいいけど報告の形式がかなり適切でえらい)

**Comment by Tatamo** [comment]
> Those who use `-d` option probably use some unknown directory structure.

`test` does not looks a good directory name for me. 
[unittest(Python)](https://docs.python.org/3.6/library/unittest.html#command-line-interface), 
[PHPUnit](https://phpunit.readthedocs.io/en/8.0/organizing-tests.html), [Jest(JavaScript)](https://jestjs.io/en/) use `tests` directory, not `test`.

**Comment by Tatamo** [comment]
> > Those who use `-d` option probably use some unknown directory structure.
> 
> `test` does not looks a good directory name for me.
> [unittest(Python)](https://docs.python.org/3.6/library/unittest.html#command-line-interface), [PHPUnit](https://phpunit.readthedocs.io/en/8.0/organizing-tests.html), [Jest(JavaScript)](https://jestjs.io/en/) use `tests` directory, not `test`.

Sorry, this is off-topic.
Thanks for your reply. I close this issue.
