### ISSUE TITLE
Add unittest to `oj download` overwrite behavior

### ISSUE THREAD

**Issue by fukatani** [kmyk/online-judge-tools#569]
In default, if user `oj download` problem and the same name sample exists, downloading sample will be skipped.
If user specify `--overwrite` option, existing file will be overwritten.
We should test this behavior.

**Comment by kmyk** [comment]
I think that we should not add options like `--overwrite`, because it will easily cause mistakes.
For example, if there is three samples (`sample-1.in`, `sample-1.out`, …, `sample-3.out`) and `oj download --overwrite` rewrite only two of them (`sample-1.in`, …, `sample-2.out`), then a very confusing state happens. `oj test` will never succeed since there is an irrelevant sample (`sample-3.in`, `sample-3.out`).

Of course, also the current behavior, just skipping, has asimilar issue.
I think that just failing is better if samples with the same name are found.

**Comment by kmyk** [comment]
The `Hacktoberfest` label is removed until we finish discussing.

**Comment by fukatani** [comment]
Thx! Basically, I agree with you. Once I close this issue.
