### ISSUE TITLE
format of commit messages

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#570]
I've used the `#ISSUE_NO: SOME_MESSAGE` format like `#123: add foo`.  I think this is good for issue-based developing with only myself, but now many people joined to develop online-judge-tools and the format may become just annoying.
So, I think we should use just simple/free format now.

@fukatani What do you think?

**Comment by fukatani** [comment]
I agree with you.

As long as PR-base development continues, every time we merge PR, commit massage like "Merge pull request #562 from pieceofeden/translate-Japanese-documents-to-English-#530" is generated automatically.
Since this message include PR number, we only have to correspond PR to issue.

*Doing the tedious work manually is easy to omit or mistake. This problem can be solved by automation.*

I think that any format is unnecessary.

**Comment by kmyk** [comment]
Okay, let's stop using the old format.

**Comment by fukatani** [comment]
For similar reasons, I want to stop to write contributors' name on readme.md. 
We can get same information from https://github.com/kmyk/online-judge-tools/graphs/contributors .

**Comment by kmyk** [comment]
Writing contributors' name on `readme.md` is important, because it means giving credits.
This is the same as we don't stop updating `CHANGELOG.md` even if there are commit logs, or as we don't stop maintaining API documents even if we can read source code.

**Comment by fukatani** [comment]
Why github contributor can't give credits?
You mean, our rate of AtCoder? 
Surely it is not understood by github contributors.

I think `CHANGELOG.md` take the role of summary of commit history.
But, Isn't one of `CHANGELOG.md` and Github release enough?
