### ISSUE TITLE
sourcerer-io/hall-of-fame

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-tools#574]
https://github.com/sourcerer-io/hall-of-fame
@kawacchu さんが https://github.com/kmyk/online-judge-tools/pull/572#issuecomment-545518228 で紹介してくれたやつです。
https://github.com/kmyk/online-judge-tools/issues/570#issuecomment-545461688 のあたりで話に挙がった「contributors の名前を手動で管理するの面倒だよね」という問題が解決されるかもしれません。

どうするのが最善かは分からないですが、とりあえず試してみたので様子を置いておきます。

[![](https://sourcerer.io/fame/kmyk/kmyk/online-judge-tools/images/0)](https://sourcerer.io/fame/kmyk/kmyk/online-judge-tools/links/0)[![](https://sourcerer.io/fame/kmyk/kmyk/online-judge-tools/images/1)](https://sourcerer.io/fame/kmyk/kmyk/online-judge-tools/links/1)[![](https://sourcerer.io/fame/kmyk/kmyk/online-judge-tools/images/2)](https://sourcerer.io/fame/kmyk/kmyk/online-judge-tools/links/2)[![](https://sourcerer.io/fame/kmyk/kmyk/online-judge-tools/images/3)](https://sourcerer.io/fame/kmyk/kmyk/online-judge-tools/links/3)[![](https://sourcerer.io/fame/kmyk/kmyk/online-judge-tools/images/4)](https://sourcerer.io/fame/kmyk/kmyk/online-judge-tools/links/4)[![](https://sourcerer.io/fame/kmyk/kmyk/online-judge-tools/images/5)](https://sourcerer.io/fame/kmyk/kmyk/online-judge-tools/links/5)[![](https://sourcerer.io/fame/kmyk/kmyk/online-judge-tools/images/6)](https://sourcerer.io/fame/kmyk/kmyk/online-judge-tools/links/6)[![](https://sourcerer.io/fame/kmyk/kmyk/online-judge-tools/images/7)](https://sourcerer.io/fame/kmyk/kmyk/online-judge-tools/links/7)

**Comment by kawacchu** [comment]
I think it cannot solve problems discussed in #572 (7 accounts at most, not reflect code review) but to visualize newcomers and enthusiasts in `README.md` is not bad idea because of two reason.
- Most (potential) users may judge using (or contributing to) applications in github by `README.md`. Hall-of-fame in `README.md` may show `online-judge-tools` is well maintained (or may motivate potential contributors).
- Just to honor owner, collaborator and contributors.
