### ISSUE TITLE
Why doesn't this repository have a .gitignore?

### ISSUE THREAD

**Issue by luchiago** [kmyk/online-judge-tools#632]
When I did `git clone` and opened the project on my machine, I was searching for the .gitignore. Is there any reason why this project does not have a `.gitignore` file?

**Comment by luchiago** [comment]
If you guys need one, I can make a Pull Request.

**Comment by kmyk** [comment]
This project has no `.gitignore` because this project has no project-specific files which should be ignored. Also in generally, when a file is not so required, I want to remove it to keep the project simple and stupid.
If you want to ignore files specific to your environment (e.g. `.DS_store`, `*~`), you should use [global gitignore](https://help.github.com/en/github/using-git/ignoring-files#create-a-global-gitignore). And personally I think we should use global gitignore even for files specific to languages (e.g. `*.pyc`, `*.egg-info/`).

ref: https://github.com/kmyk/online-judge-tools/pull/217

**Comment by luchiago** [comment]
I understand. Thanks @kmyk
