### ISSUE TITLE
What should I do if I want to add support to a new OJ?

### ISSUE THREAD

**Issue by jasonsun0310** [kmyk/online-judge-tools#657]
Is implementing the services part enough?

**Comment by kmyk** [comment]
No, you should also write tests for the new OJ ([example](https://github.com/kmyk/online-judge-tools/blob/82a473dd34aec2be48d09210319da2067c21dead/tests/service_anarchygolf.py)).

Tests are important even if your implementation is correct, because OJs will often change its implementation and so the services parts will break over time.

**Comment by jasonsun0310** [comment]
ok. I will try to add one that I play with now.

**Comment by fukatani** [comment]
https://github.com/kmyk/online-judge-tools/blob/master/CONTRIBUTING.md#how-to-add-a-new-contest-platform--%E5%AF%BE%E5%BF%9C%E3%82%B5%E3%83%BC%E3%83%93%E3%82%B9%E3%81%AE%E8%BF%BD%E5%8A%A0%E3%81%AE%E6%89%8B%E9%A0%86

This page can help you.
